[package]
name = "cli"
version = "0.1.0"
authors = ["Dustin Speckhals <dustin1114@gmail.com>"]
edition = "2018"

[dependencies.db]
path = "../db"

[dependencies]
clap = "3.0.0-beta.1"
dotenv = "0.15.0"
